### ISSUE TITLE
Font size specification

### ISSUE THREAD

**Issue by SidCool3600** [theZFJ/theZFJ.github.io#31]
Looking at the source code for Reuters + NYTimes, they all use 20px font. The site as of this writing uses a size 14px for its body. Keep in mind all three use different fonts so size will most likely be adjusted arbitrarily at the end to fit what is most pleasing

**Comment by TheSleepyAwoo** [comment]
feasibility investigation!!!! 

![image](https://github.com/theZFJ/theZFJ.github.io/assets/69493313/f06de731-003e-4086-930b-e5413716eb4f)
https://github.com/Vimux/Mainroad/blob/master/assets/css/style.css

https://discourse.gohugo.io/t/how-to-override-css-classes-with-hugo/3033/9 (this source code be good for #13 too)

gotta override the theme somehow

**Comment by TheSleepyAwoo** [comment]
14px
![image](https://github.com/theZFJ/theZFJ.github.io/assets/69493313/a80c021c-f866-4e9a-b19c-f4a113bf59a6)

15px
![image](https://github.com/theZFJ/theZFJ.github.io/assets/69493313/e409163e-0598-4405-a98f-7a02affbd846)

16px
![image](https://github.com/theZFJ/theZFJ.github.io/assets/69493313/fbc73e6e-5e3b-4fd4-bc6e-308c07fa247c)

this was all achieved with this one line in config.toml...
![image](https://github.com/theZFJ/theZFJ.github.io/assets/69493313/43d03fec-c9ad-41f5-9d25-7dc030ff781e)

...and a short custom.css file
![image](https://github.com/theZFJ/theZFJ.github.io/assets/69493313/acc2b501-338c-4ec9-84fe-44628b05fea8)

**Comment by TheSleepyAwoo** [comment]
ZFJ (15px) v. Reuters
![image](https://github.com/theZFJ/theZFJ.github.io/assets/69493313/8ae4e43f-a1f6-4b4b-960c-c960aca4f48b)

ZFJ (14px) v. Reuters
![image](https://github.com/theZFJ/theZFJ.github.io/assets/69493313/5dd0b174-b0c2-4f4c-ae31-db90624d02f5)

**Comment by TheSleepyAwoo** [comment]
i like 15px. it's a reasonable compromise.

**Comment by TheSleepyAwoo** [comment]
everything looks right. marking as resolved
