### ISSUE TITLE
caption moment

### ISSUE THREAD

**Issue by champery** [theZFJ/theZFJ.github.io#36]
the underlined part of the caption isn't supposed to appear iirc? or something like that
![image](https://github.com/theZFJ/theZFJ.github.io/assets/137745999/39de55db-babe-40a3-bb9e-a244e541a963)

**Comment by TheSleepyAwoo** [comment]
disabled feature pending further investigation

will have to go through and manually add the credits to the earlier articles (but it'll all say ZFJ Staff anyways. but still. FOR CONSISTENCY)

**Comment by TheSleepyAwoo** [comment]
meh the current solution works well and i can still make articles show up on visual credit's profile so it should all be good
